---
title: "Ternary Light Partitioning"
author:
  - "Dr. Matthew Ross"
  - 'Dr. Jim Jawitz'
  - 'Dr. Matt Cohen'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 80
---

# Motivation and Introduction {.unnumbered}

Water clarity and its components (chlorophyll *a*, total suspended sediment
(TSS), and dissolved organic carbon (DOC)) are among the most functionally
important and socially-relevant aspects of water quality. Here we propose a
method for systematically evaluating the relative contribution of each water
clarity component to total clarity, a value derived from Secchi disk depth. We
further borrow a visualization tool from soil analyses, the ternary diagram. We
build ternary diagrams that partition light partitioning between DOC, derived
algal biomass, and derived non-algal particles.

[[add conceptual ternary diagram]]

## Workflow

[[is it intentional to use particle and mass/biomass interchangably? Consider a
high-level consolidation of language in this and above section.]]

In its simplest form our workflow contains the following steps:

1.  Download all of [AquaSat](https://figshare.com/collections/AquaSat/4506140),
    a data set of four water quality parameters collated for the conterminous
    United States, and join the AquaSat pieces together to create a harmonized
    data set of the four parameters.

2.  Investigate the relationship between chlorohpyll *a*, TIS (inorganic
    sediment, derived from TSS), algal biomass (derived from chlorophyll *a*)
    and non-algal particles (derived from algal biomass and DOC). Create a
    dataset of algal biomass, non-algal particle mass, and dissolved organic
    carbon mass.

3.  Investigate data quality of AquaSat and select a subset of data where
    chlorophyll *a*, DOC, TSS and Secchi and create a dataset where all
    parameters were all measured simultaneously.

4.  Build a model that predicts light extinction using algal biomass, non-algal
    particles, and DOC where light extinction (K) is defined as:

    $$
    K = 1.4 / {Sechhi\:Disk\:Depth}
    $$

    [[note, the value I've seen for the constant is 1.7 (see Poole and Atkins
    1929), maybe cite here the associated paper for use of 1.4?]]

5.  Use this model to extract light extinction coefficients relative to each
    parameter (algal biomass, non-algal mass, DOC mass) and apply this model to
    visualizations in ternary space.

6.  Explore systematic controls on relative contribution to light extinction
    over space and time across CONUS.
